node{
    stage('code checkout'){
     git branch: 'kubernetes', url: 'https://github.com/smkorde/sample-spring-microservices'
    }
    stage('Build'){
     bat 'mvn clean install'
    }

    stage('Unit test'){
	//bat 'mvn test'
	}

    stage('Code Coverage'){
     //bat 'mvn jacoco:report'
    }
    
    stage('Code Quality'){
     //bat 'mvn sonar:sonar'
     //bat 'mvn sonar-breaker:analyze'
    }
    stage('Build Docker Image'){
        //dir ('account-service') {
        //bat 'docker build -t skorde/account-service . --no-cache'
      //  }
    }
   
    stage('Push Docker Image'){
        //bat 'docker login -u skorde -p nopassword'
        //bat 'docker push skorde/account-service'
    }
 
    stage('Deploy Application'){
        dir ('account-service') {
        bat 'kubectl apply -f deployment-account.yml'
        bat 'kubectl apply -f service-account.yml'
        }    
     }
   
    stage('Archive Artifact'){
        archiveArtifacts '**/*'
    }

  stage ('Final') {
//            build job:'customer-service', wait: false
        }  
}
